from datetime import datetime

import pydantic as pd


class Info(pd.BaseModel):
    id: str = pd.Field(alias='Id', description='Unique id number')
    kkt_reg_id: str = pd.Field(alias='KktRegId', description='Registration number')
    kkt_name: str = pd.Field(alias='KktName', description='Name')
    serial_number: str = pd.Field(alias='SerialNumber', description='Serial number')
    activation_date: datetime = pd.Field(
        alias='ActivationDate',
        description='Activation datetime'
    )
    contract_date: datetime = pd.Field(
        alias='ContractStartDate',
        description=(
            'Date of successful verification of registration number'
            'with the Federal Tax Service'
        )
    )
    contract_end_date: datetime = pd.Field(
        alias='ContractEndDate',
        description='Contract start date for "OFD.ru" services'
    )
    create_date: datetime = pd.Field(
        alias='CreateDate',
        description='Date of checkout registration in the customer\'s personal office'
    )
    fn_number: str = pd.Field(alias='FnNumber', description='Fiscal recorder number')
    sign_date: datetime = pd.Field(
        alias='SignDate', description='Date of contract signature'
    )
    payment_date: datetime = pd.Field(
        alias='PaymentDate',
        description='Date of payment of the OFD services for the cash register'
    )
    check_date: datetime = pd.Field(
        alias='CheckDate',
        description='Date of signature by qualified electronic signature'
    )
    last_doc_on_kkt_datetime: datetime = pd.Field(
        alias='LastDocOnKktDateTime',
        description=('Date and time of the last document '
                     'generated by the cash register'
                     )
    )
    last_doc_on_ofd_datetime_utc: datetime = pd.Field(
        alias='LastDocOnOfdDateTimeUtc',
        description=(
            'Date and time of the last document received by the cash register'
            'at the OFD (according to "OFD.ru" operator\'s time in UTC)'
        )
    )
    first_document_date: datetime = pd.Field(
        alias='FirstDocumentDate',
        description=(
            'Date and time when the cash register generates the first document'
        )
    )
    fiscal_address: pd.HttpUrl = pd.Field(
        alias='FiscalAddress',
        description='Cash register installation address'
    )
    fiscal_place: pd.HttpUrl = pd.Field(
        alias='FiscalPlace',
        description='Place of settlement'
    )
    path: str = pd.Field(
        alias='Path',
        description='Hierarchy of checkout locations in the customer\'s personal area'
    )
    kkt_model: str = pd.Field(alias='KktModel', description='Cash register model')
    fn_end_date: datetime = pd.Field(alias='FnEndDate', description='Date and time when the fiscal drive expires')


class KktList(pd.BaseModel):
    id: str = pd.Field(alias='Id')
    kkk_reg_id: str = pd.Field(alias='KktRegId')
    kkt_name: str = pd.Field(alias='KktName')
    serial_number: str = pd.Field(alias='SerialNumber')
    fn_number: int = pd.Field(alias='FnNumber')
    inn: str = pd.Field(alias='INN')
    group_id: str = pd.Field(alias='GroupId')
    create_date: datetime = pd.Field(alias='CreateDate')
    check_date: datetime = pd.Field(alias='CheckDate')
    activation_date: datetime = pd.Field(alias='ActivationDate')
    first_document_date: datetime = pd.Field(alias='FirstDocumentDate')
    contract_start_date: datetime = pd.Field(alias='ContractStartDate')
    last_doc_on_kkt_date_time: datetime = pd.Field(alias='LastDocOnKktDateTime')
    last_doc_on_ofd_date_time_utc: datetime = pd.Field(alias='LastDocOnOfdDateTimeUtc')
    fiscal_address: str = pd.Field(alias='FiscalAddress')
    fiscal_place: str = pd.Field(alias='FiscalPlace')
    path: str = pd.Field(alias='Path')
    kkt_model: str = pd.Field(alias='KktModel')
    fn_end_date: datetime = pd.Field(alias='FnEndDate')


class Group(pd.BaseModel):
    group_id: str = pd.Field(alias='Id')
    name: str = pd.Field(alias='Name')
    path: str = pd.Field(alias='Path')
    level: int = pd.Field(alias='Level')


class Folder(pd.BaseModel):
    agreement_id: str = pd.Field(alias='AgreementId')
    groups: list[Group] = pd.Field(alias='Groups')
